import express from "express";
import Order from "../models/Order.js";
import Item from "../models/Item.js";
import Warehouse from "../models/Warehouse.js";
import Shop from "../models/Shop.js";
import { requireAuth, requireRole } from "../middleware/auth.js";

const router = express.Router();
const guard  = requireRole("analytics");

// ── Helpers ───────────────────────────────────────────────────────────────────
const fmt = (n) =>
  new Intl.NumberFormat("en-LK", {
    style: "currency", currency: "LKR", maximumFractionDigits: 0
  }).format(Number(n) || 0);

// ── 1. Summary ────────────────────────────────────────────────────────────────
router.get("/analytics/summary", requireAuth, guard, async (_req, res) => {
  try {
    const totalRentalOrders = await Order.countDocuments({});

    const [incomeResult, incomeOverTime, orderTrendsBySource] = await Promise.all([
      Order.aggregate([{ $group: { _id: null, totalIncome: { $sum: "$paidAmount" } } }]),
      Order.aggregate([
        {
          $group: {
            _id:    { year: { $year: "$orderDate" }, month: { $month: "$orderDate" } },
            paid:   { $sum: "$paidAmount" },
            due:    { $sum: "$totalDue" },
            orders: { $sum: 1 }
          }
        },
        { $sort: { "_id.year": 1, "_id.month": 1 } }
      ]),
      Order.aggregate([
        {
          $group: {
            _id:      { source: "$orderSource", warehouseId: "$warehouseId", shopId: "$shopId" },
            count:    { $sum: 1 },
            totalDue: { $sum: "$totalDue" }
          }
        },
        { $sort: { count: -1 } }
      ])
    ]);

    const overdueCount = await Order.countDocuments({
      status: "active",
      returnDate: { $lt: new Date() }
    });

    return res.json({
      totalRentalOrders,
      totalIncome: incomeResult[0]?.totalIncome || 0,
      overdueCount,
      incomeOverTime,
      orderTrendsBySource
    });
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
});

// ── 2. Item Earnings ──────────────────────────────────────────────────────────
// Revenue generated by each piece of equipment
router.get("/analytics/item-earnings", requireAuth, guard, async (_req, res) => {
  try {
    // Earnings from multi-item line orders
    const lineItemEarnings = await Order.aggregate([
      { $unwind: "$lineItems" },
      {
        $group: {
          _id:         "$lineItems.itemId",
          itemName:    { $first: "$lineItems.itemName" },
          totalRevenue: { $sum: "$lineItems.totalAmount" },
          rentalCount:  { $sum: 1 }
        }
      }
    ]);

    // Earnings from single-item orders
    const singleItemEarnings = await Order.aggregate([
      { $match: { "lineItems.0": { $exists: false }, itemId: { $ne: null } } },
      {
        $group: {
          _id:          "$itemId",
          itemName:     { $first: "$itemSnapshot.name" },
          totalRevenue: { $sum: "$paidAmount" },
          rentalCount:  { $sum: 1 }
        }
      }
    ]);

    // Merge both sets
    const earningsMap = {};
    for (const row of [...lineItemEarnings, ...singleItemEarnings]) {
      const key = String(row._id);
      if (!earningsMap[key]) {
        earningsMap[key] = { itemId: row._id, itemName: row.itemName, totalRevenue: 0, rentalCount: 0 };
      }
      earningsMap[key].totalRevenue += row.totalRevenue;
      earningsMap[key].rentalCount  += row.rentalCount;
    }

    const earnings = Object.values(earningsMap).sort((a, b) => b.totalRevenue - a.totalRevenue);
    return res.json(earnings);
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
});

// ── 3. Location-Based Stock ────────────────────────────────────────────────────
// Stock levels for every rental location (warehouse + shop)
router.get("/analytics/location-stock", requireAuth, guard, async (_req, res) => {
  try {
    const [items, warehouses, shops] = await Promise.all([
      Item.find({}).lean(),
      Warehouse.find({}).lean(),
      Shop.find({}).lean()
    ]);

    // Items are global; active orders per location deplete "available" qty
    // We report: total items, rented (active orders), available
    const activeOrders = await Order.find({ status: "active" }).lean();

    const warehouseRentedMap = {};
    const shopRentedMap      = {};

    for (const order of activeOrders) {
      const qty = order.lineItems?.length
        ? order.lineItems.reduce((s, li) => s + li.quantity, 0)
        : (order.quantity || 0);

      if (order.orderSource === "warehouse" && order.warehouseId) {
        const k = String(order.warehouseId);
        warehouseRentedMap[k] = (warehouseRentedMap[k] || 0) + qty;
      }
      if (order.orderSource === "shop" && order.shopId) {
        const k = String(order.shopId);
        shopRentedMap[k] = (shopRentedMap[k] || 0) + qty;
      }
    }

    const totalStock = items.reduce((s, i) => s + (i.quantity || 0), 0);

    const warehouseStocks = warehouses.map((wh) => ({
      locationId:   wh._id,
      locationName: wh.name,
      locationType: "warehouse",
      totalItems:   totalStock,
      rented:       warehouseRentedMap[String(wh._id)] || 0,
      available:    Math.max(0, totalStock - (warehouseRentedMap[String(wh._id)] || 0))
    }));

    const shopStocks = shops.map((sh) => ({
      locationId:   sh._id,
      locationName: sh.name,
      locationType: "shop",
      totalItems:   totalStock,
      rented:       shopRentedMap[String(sh._id)] || 0,
      available:    Math.max(0, totalStock - (shopRentedMap[String(sh._id)] || 0))
    }));

    return res.json([...warehouseStocks, ...shopStocks]);
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
});

// ── 4. Full Stock Overview (company-wide) ─────────────────────────────────────
router.get("/analytics/stock-overview", requireAuth, guard, async (_req, res) => {
  try {
    const [items, activeOrders] = await Promise.all([
      Item.find({}).lean(),
      Order.find({ status: "active" }).lean()
    ]);

    const rentedByItem = {};
    for (const order of activeOrders) {
      if (order.lineItems?.length) {
        for (const li of order.lineItems) {
          const k = String(li.itemId);
          rentedByItem[k] = (rentedByItem[k] || 0) + li.quantity;
        }
      } else if (order.itemId) {
        const k = String(order.itemId);
        rentedByItem[k] = (rentedByItem[k] || 0) + (order.quantity || 0);
      }
    }

    const overview = items.map((item) => {
      const rented    = rentedByItem[String(item._id)] || 0;
      const available = Math.max(0, (item.quantity || 0) - rented);
      return {
        itemId:    item._id,
        itemName:  item.name,
        totalQty:  item.quantity || 0,
        rented,
        available,
        pricePerDay: item.pricePerDay || 0
      };
    });

    const totals = overview.reduce(
      (acc, r) => ({
        totalQty:  acc.totalQty  + r.totalQty,
        rented:    acc.rented    + r.rented,
        available: acc.available + r.available
      }),
      { totalQty: 0, rented: 0, available: 0 }
    );

    return res.json({ items: overview, totals });
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
});

// ── 5. Overdue Items List ─────────────────────────────────────────────────────
// All active orders past their return date, grouped by location
router.get("/analytics/overdue-items", requireAuth, guard, async (_req, res) => {
  try {
    const now = new Date();
    const [overdueOrders, warehouses, shops] = await Promise.all([
      Order.find({ status: "active", returnDate: { $lt: now } }).lean(),
      Warehouse.find({}).lean(),
      Shop.find({}).lean()
    ]);

    const whMap   = Object.fromEntries(warehouses.map((w) => [String(w._id), w.name]));
    const shopMap = Object.fromEntries(shops.map((s) => [String(s._id), s.name]));

    const overdue = overdueOrders.map((order) => {
      const daysOverdue = Math.floor((now - new Date(order.returnDate)) / (1000 * 60 * 60 * 24));
      const locationName =
        order.orderSource === "warehouse"
          ? (whMap[String(order.warehouseId)] || "Warehouse")
          : (shopMap[String(order.shopId)] || "Shop");

      const itemsSummary =
        order.lineItems?.length
          ? order.lineItems.map((li) => `${li.itemName} (x${li.quantity})`).join(", ")
          : `${order.itemSnapshot?.name || "Item"} (x${order.quantity})`;

      return {
        orderId:      order._id,
        customerName: order.customerName,
        phone:        order.phone,
        returnDate:   order.returnDate,
        daysOverdue,
        locationName,
        locationType: order.orderSource,
        itemsSummary,
        balance:      order.balance
      };
    });

    // Group by location
    const grouped = {};
    for (const row of overdue) {
      if (!grouped[row.locationName]) {
        grouped[row.locationName] = { locationName: row.locationName, locationType: row.locationType, orders: [] };
      }
      grouped[row.locationName].orders.push(row);
    }

    const result = Object.values(grouped).sort((a, b) =>
      a.locationName.localeCompare(b.locationName)
    );

    return res.json({ totalOverdue: overdue.length, locations: result, flat: overdue });
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
});

// ── 6. Current Stock Status ───────────────────────────────────────────────────
// Simple available vs rented breakdown for every item
router.get("/analytics/stock-status", requireAuth, guard, async (_req, res) => {
  try {
    const [items, activeOrders] = await Promise.all([
      Item.find({}).lean(),
      Order.find({ status: "active" }).lean()
    ]);

    const rentedByItem = {};
    for (const order of activeOrders) {
      if (order.lineItems?.length) {
        for (const li of order.lineItems) {
          const k = String(li.itemId);
          rentedByItem[k] = (rentedByItem[k] || 0) + li.quantity;
        }
      } else if (order.itemId) {
        const k = String(order.itemId);
        rentedByItem[k] = (rentedByItem[k] || 0) + (order.quantity || 0);
      }
    }

    const status = items.map((item) => {
      const rented    = rentedByItem[String(item._id)] || 0;
      const available = Math.max(0, (item.quantity || 0) - rented);
      const utilRate  = item.quantity ? Math.round((rented / item.quantity) * 100) : 0;
      return {
        itemId:       item._id,
        itemName:     item.name,
        totalQty:     item.quantity || 0,
        rented,
        available,
        utilizationRate: utilRate,
        pricePerDay:  item.pricePerDay || 0
      };
    });

    const totals = status.reduce(
      (acc, r) => ({ totalQty: acc.totalQty + r.totalQty, rented: acc.rented + r.rented, available: acc.available + r.available }),
      { totalQty: 0, rented: 0, available: 0 }
    );

    return res.json({ items: status, totals });
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
});

// ── 7. Export — CSV ───────────────────────────────────────────────────────────
router.get("/analytics/export/csv", requireAuth, guard, async (req, res) => {
  try {
    const reportType = req.query.report || "summary";
    let csvRows = [];

    if (reportType === "item-earnings") {
      const result = await Order.aggregate([
        { $unwind: { path: "$lineItems", preserveNullAndEmptyArrays: true } },
        {
          $group: {
            _id:          { $ifNull: ["$lineItems.itemName", "$itemSnapshot.name"] },
            totalRevenue: { $sum: { $ifNull: ["$lineItems.totalAmount", "$paidAmount"] } },
            rentalCount:  { $sum: 1 }
          }
        },
        { $sort: { totalRevenue: -1 } }
      ]);
      csvRows = ["Item Name,Total Revenue (LKR),Rental Count", ...result.map(
        (r) => `"${r._id || "Unknown"}",${r.totalRevenue},${r.rentalCount}`
      )];
    } else if (reportType === "overdue") {
      const now = new Date();
      const overdueOrders = await Order.find({ status: "active", returnDate: { $lt: now } }).lean();
      csvRows = ["Customer,Phone,Return Date,Days Overdue,Items,Balance (LKR)"];
      for (const o of overdueOrders) {
        const days    = Math.floor((now - new Date(o.returnDate)) / 864e5);
        const items   = o.lineItems?.length
          ? o.lineItems.map((li) => `${li.itemName} x${li.quantity}`).join(" | ")
          : `${o.itemSnapshot?.name || "Item"} x${o.quantity}`;
        csvRows.push(`"${o.customerName}","${o.phone}","${new Date(o.returnDate).toLocaleDateString("en-LK")}",${days},"${items}",${o.balance}`);
      }
    } else if (reportType === "stock-status") {
      const [items, activeOrders] = await Promise.all([Item.find({}).lean(), Order.find({ status: "active" }).lean()]);
      const rentedMap = {};
      for (const o of activeOrders) {
        if (o.lineItems?.length) {
          for (const li of o.lineItems) { rentedMap[String(li.itemId)] = (rentedMap[String(li.itemId)] || 0) + li.quantity; }
        } else if (o.itemId) { rentedMap[String(o.itemId)] = (rentedMap[String(o.itemId)] || 0) + (o.quantity || 0); }
      }
      csvRows = ["Item Name,Total Qty,Rented,Available,Price/Day (LKR),Utilization %"];
      for (const item of items) {
        const rented = rentedMap[String(item._id)] || 0;
        const avail  = Math.max(0, (item.quantity || 0) - rented);
        const util   = item.quantity ? Math.round((rented / item.quantity) * 100) : 0;
        csvRows.push(`"${item.name}",${item.quantity || 0},${rented},${avail},${item.pricePerDay || 0},${util}%`);
      }
    } else {
      // Default summary CSV
      const totalOrders = await Order.countDocuments({});
      const [income]    = await Order.aggregate([{ $group: { _id: null, total: { $sum: "$paidAmount" } } }]);
      const overdue     = await Order.countDocuments({ status: "active", returnDate: { $lt: new Date() } });
      const active      = await Order.countDocuments({ status: "active" });
      csvRows = [
        "Metric,Value",
        `Total Orders,${totalOrders}`,
        `Total Income (LKR),${income?.total || 0}`,
        `Overdue Rentals,${overdue}`,
        `Active Rentals,${active}`
      ];
    }

    const csv = csvRows.join("\n");
    res.setHeader("Content-Type", "text/csv");
    res.setHeader("Content-Disposition", `attachment; filename="rental-${reportType}-${Date.now()}.csv"`);
    return res.send(csv);
  } catch (error) {
    return res.status(500).json({ message: error.message });
  }
});

// ── 8. Export — PDF (text-based via pdfkit) ───────────────────────────────────
router.get("/analytics/export/pdf", requireAuth, guard, async (req, res) => {
  try {
    const reportType = req.query.report || "summary";
    const { default: PDFDocument } = await import("pdfkit");
    const doc = new PDFDocument({ margin: 40, size: "A4" });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="rental-${reportType}-${Date.now()}.pdf"`);
    doc.pipe(res);

    // ── Header ──
    doc.fontSize(20).fillColor("#1d4ed8").text("Rental Management System", { align: "center" });
    doc.moveDown(0.3);
    doc.fontSize(14).fillColor("#334155")
      .text(`Analytics Report — ${reportType.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())}`, { align: "center" });
    doc.fontSize(10).fillColor("#64748b")
      .text(`Generated: ${new Date().toLocaleString("en-LK")}`, { align: "center" });
    doc.moveDown(1);
    doc.moveTo(40, doc.y).lineTo(555, doc.y).strokeColor("#e2e8f0").stroke();
    doc.moveDown(0.8);

    const sectionHeader = (title) => {
      doc.fontSize(13).fillColor("#1e40af").text(title);
      doc.moveDown(0.4);
    };

    const row = (label, value, grey = false) => {
      doc.fontSize(10).fillColor(grey ? "#64748b" : "#1e293b");
      doc.text(`${label}`, 40, doc.y, { continued: true, width: 300 });
      doc.fillColor("#0f172a").text(`${value}`, { align: "right" });
    };

    if (reportType === "summary" || reportType === "overview") {
      const totalOrders = await Order.countDocuments({});
      const [income]    = await Order.aggregate([{ $group: { _id: null, total: { $sum: "$paidAmount" } } }]);
      const overdue     = await Order.countDocuments({ status: "active", returnDate: { $lt: new Date() } });
      const active      = await Order.countDocuments({ status: "active" });

      sectionHeader("📊 Summary");
      row("Total Rental Orders", totalOrders);
      doc.moveDown(0.3);
      row("Total Income", fmt(income?.total || 0));
      doc.moveDown(0.3);
      row("Active Rentals", active);
      doc.moveDown(0.3);
      row("Overdue Rentals", overdue, true);
      doc.moveDown(1);
    }

    if (reportType === "item-earnings") {
      const earnings = await Order.aggregate([
        { $unwind: { path: "$lineItems", preserveNullAndEmptyArrays: true } },
        {
          $group: {
            _id:          { $ifNull: ["$lineItems.itemName", "$itemSnapshot.name"] },
            totalRevenue: { $sum: { $ifNull: ["$lineItems.totalAmount", "$paidAmount"] } },
            rentalCount:  { $sum: 1 }
          }
        },
        { $sort: { totalRevenue: -1 } }
      ]);

      sectionHeader("💰 Item Earnings Report");
      for (const item of earnings) {
        row(`${item._id || "Unknown"}  (${item.rentalCount} rental${item.rentalCount !== 1 ? "s" : ""})`, fmt(item.totalRevenue));
        doc.moveDown(0.25);
        if (doc.y > 720) { doc.addPage(); }
      }
    }

    if (reportType === "overdue") {
      const now    = new Date();
      const orders = await Order.find({ status: "active", returnDate: { $lt: now } }).lean();

      sectionHeader(`⚠️ Overdue Items — ${orders.length} order(s)`);
      for (const o of orders) {
        const days  = Math.floor((now - new Date(o.returnDate)) / 864e5);
        const items = o.lineItems?.length
          ? o.lineItems.map((li) => `${li.itemName} x${li.quantity}`).join(", ")
          : `${o.itemSnapshot?.name || "Item"} x${o.quantity}`;
        doc.fontSize(10).fillColor("#1e293b").text(`${o.customerName} — ${items} — ${days} day(s) overdue — Balance: ${fmt(o.balance)}`);
        doc.fontSize(9).fillColor("#64748b").text(`  Phone: ${o.phone}  |  Due: ${new Date(o.returnDate).toLocaleDateString("en-LK")}`);
        doc.moveDown(0.4);
        if (doc.y > 720) { doc.addPage(); }
      }
    }

    if (reportType === "stock-status") {
      const [items, activeOrders] = await Promise.all([Item.find({}).lean(), Order.find({ status: "active" }).lean()]);
      const rentedMap = {};
      for (const o of activeOrders) {
        if (o.lineItems?.length) {
          for (const li of o.lineItems) { rentedMap[String(li.itemId)] = (rentedMap[String(li.itemId)] || 0) + li.quantity; }
        } else if (o.itemId) { rentedMap[String(o.itemId)] = (rentedMap[String(o.itemId)] || 0) + (o.quantity || 0); }
      }

      sectionHeader("📦 Stock Status Report");
      for (const item of items) {
        const rented = rentedMap[String(item._id)] || 0;
        const avail  = Math.max(0, (item.quantity || 0) - rented);
        doc.fontSize(10).fillColor("#1e293b")
          .text(`${item.name}`, { continued: true, width: 280 });
        doc.fillColor("#0f172a")
          .text(`Total: ${item.quantity}  Rented: ${rented}  Available: ${avail}`, { align: "right" });
        doc.moveDown(0.25);
        if (doc.y > 720) { doc.addPage(); }
      }
    }

    doc.end();
  } catch (error) {
    if (!res.headersSent) {
      res.status(500).json({ message: error.message });
    }
  }
});

export default router;
